name: GetDockerImage

on:
  workflow_dispatch: ~

env:
  ALIYUN_REGISTRY: "${{ vars.ALIYUN_REGISTRY }}"
  ALIYUN_NAME_SPACE: "${{ vars.ALIYUN_NAME_SPACE }}"
  ALIYUN_REGISTRY_USERNAME: "${{ secrets.ALIYUN_REGISTRY_USERNAME }}"
  ALIYUN_REGISTRY_PASSWORD: "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}"
  IMAGE_LIST: "${{ vars.IMAGE_LIST }}"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Show disk space before
      run: |
        echo "Before freeing up disk space"
        echo "=============================================================================="
        df -hT
        echo "=============================================================================="
        
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 2048
        swap-size-mb: 128
        remove-dotnet: 'true'
        remove-haskell: 'true'
        remove-android: 'true'
        remove-codeql: 'true'
        build-mount-path: '/var/lib/docker/'
        
    - name: Restart docker
      run: sudo service docker restart

    - name: Show disk space after
      run: |
        echo "Free up disk space complete"
        echo "=============================================================================="
        df -hT
        echo "=============================================================================="        

    - name: Login Aliyun
      run: |
        docker login -u $ALIYUN_REGISTRY_USERNAME -p $ALIYUN_REGISTRY_PASSWORD $ALIYUN_REGISTRY

    - name: Pull and push images
      run: |
        for image in $IMAGE_LIST; do
          echo "image item: "$image
          IFS='/' read -r name_space name_tag <<< "$image"
          echo "namespace: "$name_space
          echo "name_tag: "$name_tag
          IFS=':' read -r image_name image_tag <<< "$name_tag"
          echo "image_name: "$image_name
          echo "image_tag: "$image_tag
          old_image_tag="$name_space/$image_name:$image_tag"
          echo "old_image_tag: "$old_image_tag
          new_image_tag="$ALIYUN_REGISTRY/$ALIYUN_NAME_SPACE/$image_name:$image_tag"
          echo "new_image_tag: "$new_image_tag
          docker pull $old_image_tag
          echo "pull old image finish"
          docker tag $old_image_tag $new_image_tag
          echo "tag image finish"
          docker push $new_image_tag
          echo "push new image finish"
          docker rmi $old_image_tag $new_image_tag        
        done
